parameters:
  name: ''
  pool: ''
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
  - script: python -m pip install --upgrade pip && pip install -r pyrunner/requirements.txt
    displayName: 'Install dependencies'
  - script: script: |
      pip install flake8
      flake8 --max-line-length=119
    displayName: 'Code style check'
